version: '3'

services:

    reverse-proxy:
        image: nginx:latest
        container_name: reverse_proxy
        depends_on:
            - dashboard
            - rng
            - calculator
        volumes:
            - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80

    dashboard:
        image: dashboard
        container_name: dashboard
        build:
            context: ./dashboard
        depends_on:
            - rng
            - calculator
        ports:
            - 8080:80
        restart: on-failure

    rng:
        image: rng
        container_name: rng
        build:
            context: ./rng
        ports:
            - 5001:5001
        restart: on-failure

    calculator:
        image: calculator
        container_name: calculator
        build:
            context: ./calculator
        ports:
            - 5002:5002
        restart: on-failure
